#ifndef ONEPIECE_BASE_CRYPTO_H_
#define ONEPIECE_BASE_CRYPTO_H_

#define AES_SUCCESS                 0
#define AES_UNSUPPORTED_MODE        (AES_SUCCESS - 1)
#define AES_UNSUPPORTED_DIRECTION   (AES_SUCCESS - 2)
#define AES_UNSUPPORTED_KEY_LENGTH  (AES_SUCCESS - 3)
#define AES_RIJNDAEL_BAD_KEY        (AES_SUCCESS - 4)
#define AES_NOT_INITIALIZED         (AES_SUCCESS - 5)
#define AES_RIJNDAEL_BAD_DIRECTION  (AES_SUCCESS - 6)
#define AES_RIJNDAEL_CORRUPTED_DATA (AES_SUCCESS - 7)
#define AES_BADPARMA                (AES_SUCCESS - 8)

#endif  // ONEPIECE_BASE_CRYPTO_H_
